str = ''
str += '<div id="header">'
str += ''
str += '	<div class="util">'
str += '		<ul>'
str += '			<li><a href="index.html">실로암 요양원 홈페이지</a></li>'
str += '		</ul>'
str += '	</div>'
str += ''
str += '	<div class="h_group">'
str += ''
str += '		<div>'
str += '			<h1>'
str += '				<a href="index.html"><img src="img/common/logo.png" alt="실로암요양원" /></a>'
str += '			</h1>'
str += '			<div id="gnb">'
str += '				<button type="button" class="btn_menu"><span class="blind">전체메뉴 열기</span></button>'
str += '				<div class="box">'
str += '					<button type="button" class="btn_close"><span class="blind">전체메뉴 닫기</span></button>'
str += '					<ul>'
str += '						<li><a href="#"><span>직원 알림마당</span></a></li>'
str += '					</ul>'
str += '				</div>'
str += '			</div>'
str += '		</div>'
str += ''
str += '	</div>'
str += ''
str += '</div>'

document.write(str);