str = ''
str += '<div id="footer">'
str += '	<div class="f_wrap">'
str += '		<div class="f_holder">'
str += '			<p class="txt">FAMILY SITE</a></p>'
str += ''
str += '			<div class="f_selector">'
str += '				<p class="icon"><img src="img/common/list.png" alt="열림"></p>'
str += '			</div>'
str += ''
str += '			<div class="f_menu">'
str += '				<ul>'
str += '					<li><a href="#none">실로암</a></li>'
str += '					<li><a href="#none">이야기</a></li>'
str += '				</ul>'
str += '			</div>'
str += '		</div>'
str += '		<div class="info">'
str += '			<ul>'
str += '				<li><a href="#">개인정보처리방침</a><span class="bar"></span></li>'
str += '				<li><a href="#">이메일무단수집거부</a><span class="bar"></span></li>'
str += '				<li><a href="#">찾아오시는길</a></li>'
str += '			</ul>'
str += '			<p>경기도 양주시 광적면 쇠장이길 656 실로암 요양원</p>'
str += '			<ul class="add">'
str += '				<li>전화번호 : <a href="tel:031-876-2900">031-876-2900</a><span class="bar"></span></li>'
str += '				<li>팩스 : 031-876-2990<span class="bar"></span></li>'
str += '				<li>이메일 : silwel@chol.com</li>'
str += '			</ul>'
str += '		</div>'
str += '		<div class="family">'
str += '			<a href="#none" class="f_btn">패밀리사이트</a>'
str += '			<ul class="f_list">'
str += '				<li><a href="#none">실로암</a></li>'
str += '				<li><a href="#none">이야기</a></li>'
str += '			</ul>'
str += '			<a href="#none" class="submit">확인</a>'
str += '		</div>'
str += '	</div>'
str += '</div>'

document.write(str)