str = ''
str += '<div id="header">'
str += ''
str += '	<div class="util">'
str += '		<ul>'
str += '			<li><a href="index.html">Home</a><span class="bar"></span></li>'
str += '			<li><a href="sitemap.html">사이트맵</a><span class="bar"></span></li>'
str += '			<li><a href="login.html">직원전용</a></li>'
str += '		</ul>'
str += '	</div>'
str += ''
str += '	<div class="h_group">'
str += ''
str += '		<div>'
str += '			<h1>'
str += '				<a href="index.html"><img src="img/common/logo.png" alt="실로암요양원" /></a>'
str += '			</h1>'
str += '			<div id="gnb">'
str += '				<button type="button" class="btn_menu">전체메뉴 열기</button>'
str += '				<div class="box">'
str += '					<button type="button" class="btn_close">전체메뉴 닫기</button>'
str += '					<ul>'
str += '						<li><a href="#"><span>요양원소개</span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="greeting.html"><span>인사말</span></a></li>'
str += '									<li><a href="intro.html"><span>법인소개</span></a></li>'
str += '									<li><a href="mission.html"><span>미션과비전</span></a></li>'
str += '									<li><a href="orga.html"><span>조직도</span></a></li>'
str += '									<li><a href="staff.html"><span>직원소개</span></a></li>'
str += '									<li><a href="history.html"><span>연혁</span></a></li>'
str += '									<li><a href="map.html"><span>오시는길</span></a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>시설안내</span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="city.html"><span>시설안내</span></a></li>'
str += '									<li><a href="camp.html"><span>입소안내</span></a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>프로그램</span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="lecture.html"><span>프로그램안내</span></a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>사랑나눔</span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="support.html"><span>후원신청</span></a></li>'
str += '									<li><a href="volunteer.html"><span>자원봉사신청</span></a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="#"><span>알림마당</span></a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="s_list.html"><span>공지사항</span></a></li>'
str += '									<li><a href="g_list.html"><span>실로암소식지</span></a></li>'
str += '									<li><a href="p_list.html"><span>포토갤러리</span></a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '					</ul>'
str += '				</div>'
str += '			</div>'
str += '		</div>'
str += ''
str += '	</div>'
str += ''
str += '</div>'

document.write(str);